# -*- coding: utf-8 -*-
"""9.4 Feasibility Test and Initial Exploration——revised .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vJNWVntZsgccxC94vQutZCb-nK6N7G9n

# 0-Set Up
"""

import io, requests, pandas as pd

ENDPOINT = "https://publications.europa.eu/webapi/rdf/sparql"
AUTH = "http://publications.europa.eu/resource/authority/"
PREFIXES = """
PREFIX cdm: <http://publications.europa.eu/ontology/cdm#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
"""
ENG = f"<{AUTH}language/ENG>"

Q_EUROVOC = f"""{PREFIXES}
SELECT DISTINCT ?work ?agent ?type ?date ?title WHERE {{
  ?work cdm:work_is_about_concept_eurovoc <http://eurovoc.europa.eu/3030> ;
        cdm:work_created_by_agent ?agent ;
        cdm:work_date_document ?date .
  OPTIONAL {{ ?work cdm:work_has_resource-type ?type }}
  OPTIONAL {{ ?e cdm:expression_belongs_to_work ?work ;
                cdm:expression_uses_language {ENG} ;
                cdm:expression_title ?title }}
  FILTER(?date >= "2020-01-01"^^xsd:date)
}}"""

Q_TITLE = f"""{PREFIXES}
SELECT DISTINCT ?work ?agent ?type ?date ?title WHERE {{
  ?e cdm:expression_belongs_to_work ?work ;
     cdm:expression_uses_language {ENG} ;
     cdm:expression_title ?title .
  ?work cdm:work_created_by_agent ?agent ;
        cdm:work_date_document ?date .
  OPTIONAL {{ ?work cdm:work_has_resource-type ?type }}
  FILTER(?date >= "2020-01-01"^^xsd:date)
  FILTER(CONTAINS(LCASE(STR(?title)), "artificial intelligence"))
}}"""

def run(q):
    r = requests.get(ENDPOINT,params={"query": q},
        headers={"Accept": "text/csv"},timeout=180
    )
    r.raise_for_status()

    df = pd.read_csv(io.StringIO(r.text))

    for c in df.columns:
        df[c] = (df[c].astype("string")
            .str.replace(AUTH, "", regex=False)
        )

    return df

COMMISSION = {"COM","SG","SJ","CNECT","RTD","COMP","JUST","EMPL","GROW","HOME","TRADE",
              "SANTE","ENER","MOVE","EAC","ECFIN","FISMA","AGRI","ENV","CLIMA","DEFIS",
              "DIGIT","JRC","EISMEA","EASME","HADEA","REA","ERCEA","CINEA","EACEA","ESTAT",
              "OLAF","TAXUD","MARE","REGIO","INTPA","NEAR","ECHO","BUDG","HR","COMM","OIB"}

def institution(agent):
    code = str(agent).split("/")[-1]
    if code == "CONSIL": return "Council"
    if code == "EP" or code.startswith("EP_"): return "Parliament"
    if code in COMMISSION: return "Commission"
    return None

# scope rules: CELLAR resource type -> in/out (same as data/doc_types.csv)
IN_SCOPE = {"COMMUNIC","JOINT_COMMUNIC","COMMUNIC_POSIT","PAPER_WHITE","SWD",
            "IMPACT_ASSESS","IMPACT_ASSESS_SUM","IMPACT_ASSESS_INCEP","EVL",
            "FACT_SUM_REPORT_CONSULT","PROP_REG","PROP_DIR","PROP_DEC","RECO","RECO_DEC",
            "REPORT","REPORT_EP","REPORT_DRAFT_EP_CMT","OWNINI_RES","RES_LEGIS","RES",
            "ADOPT_TEXT","OPIN_EP_CMT","OPIN_LETTER_EP_CMT","AMEND_LIST_EP","NOTE",
            "ITEM_IA_NOTE","NOTE_INFO","CONCL","POSIT","DECLAR","STAT_REASON","STAT",
            "AGREE_PROV"}

u = pd.concat([run(Q_EUROVOC), run(Q_TITLE)])
u["institution"] = u["agent"].map(institution)
u = u.dropna(subset=["institution"])
u["type"] = u["type"].str.replace("resource-type/", "", regex=False)

# exclude works attributed to more than one institution (co-signed acts, joint declarations)
n_inst = u.drop_duplicates(["work", "institution"]).groupby("work")["institution"].nunique()

works = (u.groupby("work")
           .agg(institution=("institution", "first"), type=("type", "first"),
                date=("date", "first"), title=("title", "first"))
           .reset_index())
works["joint"] = works["work"].map(n_inst).gt(1)
works["in_scope"] = works["type"].isin(IN_SCOPE) & ~works["joint"]

core = works[works["in_scope"]]
print("Found:", len(works), "| In scope:", len(core))
print(core.groupby("institution").size())
print(core.assign(year=pd.to_datetime(core["date"]).dt.year)
          .pivot_table(index="year", columns="institution", values="work",
                       aggfunc="count", fill_value=0))

retrieval_date = datetime.date.today().isoformat()
works.to_csv(f"data/raw_works_{retrieval_date}.csv", index=False)
print(f"Retrieved {len(works)} works on {retrieval_date}")
print("Observation period: 2020-01-01 to present")
print("Retrieval strategy: EuroVoc AI concept OR English title contains 'artificial intelligence'")

"""# 1-Feasibility Assessment

## 1.1 Access Feasibility

## 1.2 Scope Feasibility
"""

works["year"] = pd.to_datetime(works["date"]).dt.year
core = works[works["in_scope"]]  # 重新生成一次core，确保它也带上year这一列

print(works.columns.tolist())  # 确认year已经加上了

print("\nRaw corpus size:", works.shape)
print("\nDocuments by institution (raw):")
print(works["institution"].value_counts())

print("\nDocuments by year and institution (raw):")
print(works.pivot_table(index="year", columns="institution",
                         values="work", aggfunc="count", fill_value=0))

print("\nDocument types (raw):")
print(works.groupby(["institution", "type"]).size().sort_values(ascending=False))

print("\nJoint/co-signed works excluded:", works["joint"].sum())

"""From the result above:
The CELLAR-based retrieval strategy is technically feasible and yields a sufficiently large cross-institutional corpus, but the initial retrieval contains substantial heterogeneity in document type and institutional coverage. This makes eligibility filtering and controls for document type and time necessary before substantive framing analysis.
"""

TYPE_REASONS = {
    "PUB_GEN": "research output (JRC/DG reports), not institutional position",
    "NOTE_COVER": "Council forwarded but did not author",
    "CORRIGENDUM": "administrative correction, not substantive",
    "PLENARY_MINUTES_EP": "procedural minutes",
    "FACTSHEET": "not institutional position",
    "ACT_LEGIS": "adopted legal act, co-signed across institutions",
    "REG": "adopted regulation, co-signed",
    "DEC": "adopted decision, co-signed",
    "REG_IMPL": "adopted implementing regulation, legal act",
    "DEC_IMPL": "adopted implementing decision, legal act",
    "PROP_ACT": "Council mirror copy of Commission proposal, not Council-authored",
    "STU": "commissioned study, research output",
    "NOTICE": "competition-clearance administrative notice, not AI policy statement",
    "ITEM_I_NOTE": "procedural item note, not substantive position",
    "FACT_SUM_REPORT_CONSULT": "included per team decision: summarizes consultation input relevant to institutional position",
    "NOTE_INFO": "included per team decision: informational note treated as substantive enough for corpus",
    "AGREE_PROV": "included per team decision: provisional agreement text retained; flagged for inherited-share quantification given co-negotiated content",
}

doc_types_rows = []
for t in sorted(works["type"].unique()):
    decision = "include" if t in IN_SCOPE else "exclude"
    reason = TYPE_REASONS.get(t, "not in scope list; see manual spot-check" if decision == "exclude" else "")
    doc_types_rows.append({"type": t, "decision": decision, "reason": reason})

doc_types_df = pd.DataFrame(doc_types_rows)
doc_types_df.to_csv("data/doc_types.csv", index=False)
print(f"\nSaved scope decisions for {len(doc_types_df)} types to data/doc_types.csv")

"""## Ambiguous Test"""

AMBIGUOUS_TYPES = ["EVL", "STAT", "FACT_SUM_REPORT_CONSULT", "NOTE_INFO", "AGREE_PROV"]
# 修改：NOTICE已经确认排除，不用再spot-check；换成三个新确认include的type，

for t in AMBIGUOUS_TYPES:
    subset = works[works["type"] == t][["institution", "date", "title"]]
    print(f"\n{'='*80}\n{t}  (n={len(subset)})")
    print(subset.to_string(index=False))

for t in AMBIGUOUS_TYPES:
    subset = works[works["type"] == t][["institution", "date", "title"]]
    print(f"\n{'='*80}\n{t}  (n={len(subset)})")
    print(subset.to_string(index=False))

"""Manual Audit"""

# Show a random sample from each institution
sample = (
    df.groupby("institution", group_keys=False)
      .apply(lambda x: x.sample(min(5, len(x)), random_state=42))
)

print(sample[["institution", "type", "date", "title"]].to_string(index=False))

"""## 1.4 Limitation-- metadata completeness

"""

metadata_cols = ["work", "institution", "date", "type", "title"]

print("\nMissing values overall:")
print(works[metadata_cols].isna().sum())

print("\nMissing values by institution:")
print(works.groupby("institution")[metadata_cols].apply(
    lambda x: x.isna().sum(), include_groups=False))

"""The results show work, institution, date,type short have no zeros. It signals that CELLAR provides sufficiently complete core metadata for constructing the institutional comparison corpus.

However, title metadata are slightly less complete, with 13 records (2.05%) missing titles.

Missing-title records are disproportionately concentrated in the Council subset, suggesting that metadata completeness may vary somewhat by institution.

# 2. Initial Exploration

## 2.1 Basic Counts
"""

year_inst = core.pivot_table(index="year", columns="institution",
                              values="work", aggfunc="count", fill_value=0)
print("\nIn-scope documents by year and institution:")
print(year_inst)

type_inst = core.groupby(["institution", "type"]).size().sort_values(ascending=False)
print("\nIn-scope documents by type (top 15):")
print(type_inst.head(15))

summary_stats = core.groupby("institution").agg(
    n_docs=("work", "count"), n_types=("type", "nunique"),
    earliest=("date", "min"), latest=("date", "max"))
print("\nPer-institution summary (in-scope):")
print(summary_stats)

examples = (
    core.groupby("institution", group_keys=False)
        .apply(lambda x: x.sort_values("date").iloc[[0, -1]])
)
print("\nRepresentative examples:")
print(examples[["institution", "type", "date", "title"]].to_string(index=False))

"""## 2.2 Figure"""

# Add a figure folder
!mkdir -p figures

# Code
import numpy as np
import matplotlib.pyplot as plt
import os

os.makedirs("figures", exist_ok=True)

years = year_inst.index.tolist()
x = np.arange(len(years))
width = 0.25
colors = {"Commission": "#2E5EAA", "Parliament": "#8B3A3A", "Council": "#888888"}

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5.5))
for i, inst in enumerate(["Commission", "Parliament", "Council"]):
    offset = (i - 1) * width
    ax1.bar(x + offset, year_inst[inst], width, label=inst, color=colors[inst], alpha=0.85)
    ax1.plot(x + offset, year_inst[inst], color=colors[inst], marker="o", markersize=4, linewidth=1.2)

for year_mark, label in [(2021, "AI Act\nproposed"), (2025, "Digital Omnibus\non AI proposed")]:
    if year_mark in years:
        xpos = years.index(year_mark) - 0.5
        ax1.axvline(x=xpos, color="grey", linestyle=":", linewidth=1)
        ax1.text(xpos + 0.05, ax1.get_ylim()[1]*0.95, label, fontsize=7.5, color="grey", va="top")

ax1.set_xticks(x); ax1.set_xticklabels(years)
ax1.set_xlabel("Year"); ax1.set_ylabel("In-scope documents")
ax1.set_title("(a) In-scope AI documents by year")
ax1.legend(title="Institution", fontsize=8)


type_inst_wide = core.groupby(["institution", "type"]).size().unstack(fill_value=0)
type_inst_wide.plot(kind="barh", stacked=True, ax=ax2, colormap="tab20")
ax2.set_xlabel("documents"); ax2.set_title("(b) Composition by document type")
ax2.legend(fontsize=6, bbox_to_anchor=(1.02, 1), loc="upper left")

fig.suptitle(f"Figure 1. AI-related institutional documents retrievable from CELLAR "
             f"(N={len(core)} in scope of {len(works)} found; 2020–2026)", fontsize=10, y=1.02)
plt.tight_layout()
plt.savefig("figures/week2_combined.png", dpi=150, bbox_inches="tight")
plt.show()